replicaCount: 1

image:
  repository: apache/nifi
  tag: "2.4
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 8080

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 10Gi

resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

properties:
  sensitiveKey: "my-sensitive-key-123456789012"
  singleUser:
    username: "admin"
    password: "admin1234567890" # Must be at least 12 characters

nifi:
  properties:
    webHttpPort: 8080
    isClustered: false